/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/socket_serialize.proto */

#ifndef PROTOBUF_C_proto_2fsocket_5fserialize_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fsocket_5fserialize_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SocketSerialize SocketSerialize;


/* --- enums --- */


/* --- messages --- */

struct  _SocketSerialize
{
  ProtobufCMessage base;
  /*
   *tcp info
   */
  ProtobufCBinaryData ktlsbuf;
  uint64_t seq;
  uint64_t ack;
  ProtobufCBinaryData sendq;
  uint64_t sendq_len;
  uint64_t unsentq_len;
  ProtobufCBinaryData recvq;
  uint64_t recvq_len;
  uint64_t self_addr;
  uint32_t self_port;
  uint64_t peer_addr;
  uint64_t peer_mac;
  uint32_t peer_port;
  uint32_t mss;
  uint32_t send_wscale;
  uint32_t recv_wscale;
  uint64_t timestamp;
  uint64_t snd_wl1;
  uint64_t snd_wnd;
  uint32_t max_window;
  uint64_t rev_wnd;
  uint64_t rev_wup;
  int32_t msg_type;
  uint32_t ctrl_src_port;
  /*
   * http client
   */
  int32_t method;
  char *bucket_name;
  char *object_name;
  char *uri_str;
  int64_t object_size;
  int32_t acting_primary_osd_id;
};
#define SOCKET_SERIALIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&socket_serialize__descriptor) \
    , {0,NULL}, 0, 0, {0,NULL}, 0, 0, {0,NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


/* SocketSerialize methods */
void   socket_serialize__init
                     (SocketSerialize         *message);
size_t socket_serialize__get_packed_size
                     (const SocketSerialize   *message);
size_t socket_serialize__pack
                     (const SocketSerialize   *message,
                      uint8_t             *out);
size_t socket_serialize__pack_to_buffer
                     (const SocketSerialize   *message,
                      ProtobufCBuffer     *buffer);
SocketSerialize *
       socket_serialize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   socket_serialize__free_unpacked
                     (SocketSerialize *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SocketSerialize_Closure)
                 (const SocketSerialize *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor socket_serialize__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fsocket_5fserialize_2eproto__INCLUDED */
