/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: info_to_migrate.proto */

#ifndef PROTOBUF_C_info_5fto_5fmigrate_2eproto__INCLUDED
#define PROTOBUF_C_info_5fto_5fmigrate_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _InfoToMigrate InfoToMigrate;


/* --- enums --- */


/* --- messages --- */

struct  _InfoToMigrate
{
  ProtobufCMessage base;
  /*
   *tls info: depends on tlse serialization
   */
  ProtobufCBinaryData buf;
  /*
   *tcp info
   */
  uint64_t seq;
  uint64_t ack;
  ProtobufCBinaryData sendq;
  uint64_t sendq_len;
  uint64_t unsentq_len;
  ProtobufCBinaryData recvq;
  uint64_t recvq_len;
  uint64_t self_addr;
  uint32_t self_port;
  uint64_t peer_addr;
  uint32_t peer_port;
  uint32_t mss;
  uint32_t send_wscale;
  uint32_t recv_wscale;
  uint64_t timestamp;
  uint64_t snd_wl1;
  uint64_t snd_wnd;
  uint32_t max_window;
  uint64_t rev_wnd;
  uint64_t rev_wup;
  int32_t msg_type;
  uint32_t ctrl_src_port;
};
#define INFO_TO_MIGRATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&info_to_migrate__descriptor) \
    , {0,NULL}, 0, 0, {0,NULL}, 0, 0, {0,NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* InfoToMigrate methods */
void   info_to_migrate__init
                     (InfoToMigrate         *message);
size_t info_to_migrate__get_packed_size
                     (const InfoToMigrate   *message);
size_t info_to_migrate__pack
                     (const InfoToMigrate   *message,
                      uint8_t             *out);
size_t info_to_migrate__pack_to_buffer
                     (const InfoToMigrate   *message,
                      ProtobufCBuffer     *buffer);
InfoToMigrate *
       info_to_migrate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   info_to_migrate__free_unpacked
                     (InfoToMigrate *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*InfoToMigrate_Closure)
                 (const InfoToMigrate *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor info_to_migrate__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_info_5fto_5fmigrate_2eproto__INCLUDED */
